# TODO: add test matrix for all SOM VMs
language: python

python:
  - "2.7"

install:
  - git clone --depth 1 https://github.com/smarr/PySOM.git

# command to run tests
script:
  # Run unit tests with PySOM
  - cd PySOM && git --no-pager log -n 1 && ./som.sh -cp ../Smalltalk ../TestSuite/TestHarness.som
