dist: xenial
sudo: false

jobs:
  include:
    - language: cpp
      addons: {apt: {packages: [cmake, libcppunit-dev]}}
      env: SOM=SOMpp       REPO=SOMpp.git       BUILD="cmake . && make SOM++" SOM=./som.sh

    - language: c
      env: SOM=CSOM        REPO=CSOM.git        BUILD=make    SOM=./som.sh COMPILER=gcc ARCH=64bit

    # JsSOM can't currently be parameterized with another core lib, so, we can't really test it
    # - language: node_js
    #   env: SOM=JsSOM       REPO=JsSOM.git       BUILD=make    SOM=./som.sh

    - language: python
      env: SOM=PySOM       REPO=PySOM.git       BUILD=""      SOM=./som.sh  PYTHON=python
      python:
        - "2.7"

    - language: python
      env: SOM=RPySOM      REPO=RPySOM.git      BUILD=""      SOM=./som.sh  PYTHON=python
      python:
        - "2.7"
      before_script:
        - |
          cd som-vm
          travis_retry wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-src.tar.bz2
          tar -xjf pypy2.7-v7.0.0-src.tar.bz2
          mv pypy2.7-v7.0.0-src pypy
          cd ..

    - language: python
      env: SOM=RTruffleSOM REPO=RTruffleSOM.git BUILD=""      SOM=./som.sh  PYTHON=python
      python:
        - "2.7"
      before_script:
        - |
          cd som-vm
          travis_retry wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-src.tar.bz2
          tar -xjf pypy2.7-v7.0.0-src.tar.bz2
          mv pypy2.7-v7.0.0-src pypy
          cd ..

    - language: java
      dist: trusty
      env: SOM=SOM         REPO=som-java.git    BUILD=make    SOM=./som.sh
      jdk: [oraclejdk8]
      addons: {apt: {packages: [libc6-dev-i386]}}

    - language: java
      dist: trusty
      env: SOM=TruffleSOM  REPO=TruffleSOM.git  BUILD="ant jar"    SOM="./som -G"
      jdk: [oraclejdk8]
      addons: {apt: {packages: [libc6-dev-i386]}}

    - language: java
      dist: trusty
      env: SOM=spec
      jdk: [oraclejdk8]

  allow_failures:
    # - env: SOM=JsSOM       REPO=JsSOM.git       BUILD=make    SOM=./som.sh
    - env: SOM=PySOM       REPO=PySOM.git       BUILD=""      SOM=./som.sh  PYTHON=python
    - env: SOM=RPySOM      REPO=RPySOM.git      BUILD=""      SOM=./som.sh  PYTHON=python

install:
  - |
    # Install Dependencies and Load SOM VM
    if [ "$SOM" != "spec" ]
    then
      pip install -q pyyaml

      if [ "$TRAVIS_PULL_REQUEST" = "false" ]
      then
        export BRANCH_NAME=$TRAVIS_BRANCH
        export GITHUB_USER=`echo $TRAVIS_REPO_SLUG | cut -d/ -f1`
      else
        export BRANCH_NAME=$TRAVIS_PULL_REQUEST_BRANCH
        export GITHUB_USER=`echo $TRAVIS_PULL_REQUEST_SLUG | cut -d/ -f1`
        export PR_TARGET_USER=`echo $TRAVIS_REPO_SLUG | cut -d/ -f1`
      fi
      echo "Get https://github.com/$GITHUB_USER/$REPO at branch $BRANCH_NAME for testing"
      git clone --branch $BRANCH_NAME --depth 1 https://github.com/$GITHUB_USER/$REPO som-vm || git clone --depth 1 https://github.com/$GITHUB_USER/$REPO som-vm || git clone --depth 1 https://github.com/$PR_TARGET_USER/$REPO som-vm
    fi

# command to run tests
script:
  - |
    set -e
    if [ "$SOM" = "spec" ]
    then
      cd specification
      make test
    else
      ./TestSuite/BasicInterpreterTests/number-of-tests.sh
      export ST_DIR=`pwd`/Smalltalk
      cd som-vm
      git --no-pager log -n 1
      eval $BUILD
      $SOM -cp ../Smalltalk ../TestSuite/TestHarness.som
    fi
