dist: xenial
sudo: false

matrix:
  include:
    - language: cpp
      addons: {apt: {packages: [cmake, libcppunit-dev]}}
      env: SOM=SOMpp       REPO=https://github.com/SOM-st/SOMpp.git       BUILD="cmake . && make SOM++" SOM=./som.sh

    - language: c
      env: SOM=CSOM        REPO=https://github.com/SOM-st/CSOM.git        BUILD=make    SOM=./som.sh COMPILER=gcc ARCH=64bit

    # JsSOM can't currently be parameterized with another core lib, so, we can't really test it
    # - language: node_js
    #   env: SOM=JsSOM       REPO=https://github.com/SOM-st/JsSOM.git       BUILD=make    SOM=./som.sh

    - language: python
      env: SOM=PySOM       REPO=https://github.com/SOM-st/PySOM.git       BUILD=""      SOM=./som.sh  PYTHON=python
      python:
        - "2.7"

    - language: python
      env: SOM=RPySOM      REPO=https://github.com/SOM-st/RPySOM.git      BUILD=""      SOM=./som.sh  PYTHON=python
      python:
        - "2.7"
      before_script:
        - |
          cd som-vm
          travis_retry wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-src.tar.bz2
          tar -xjf pypy2.7-v7.0.0-src.tar.bz2
          mv pypy2.7-v7.0.0-src pypy
          cd ..

    - language: python
      env: SOM=RTruffleSOM REPO=https://github.com/SOM-st/RTruffleSOM.git BUILD=""      SOM=./som.sh  PYTHON=python
      python:
        - "2.7"
      before_script:
        - |
          cd som-vm
          travis_retry wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-src.tar.bz2
          tar -xjf pypy2.7-v7.0.0-src.tar.bz2
          mv pypy2.7-v7.0.0-src pypy
          cd ..

    - language: java
      dist: trusty
      env: SOM=SOM         REPO=https://github.com/SOM-st/som-java.git    BUILD=make    SOM=./som.sh
      jdk: [oraclejdk8]
      addons: {apt: {packages: [libc6-dev-i386]}}
      
    - language: java
      dist: trusty
      env: SOM=TruffleSOM  REPO=https://github.com/SOM-st/TruffleSOM.git  BUILD=make    SOM="./som -G"
      jdk: [oraclejdk8]
      addons: {apt: {packages: [libc6-dev-i386]}}
      
    - language: java
      env: SOM=spec
      jdk: [oraclejdk8]

  allow_failures:
    # - env: SOM=JsSOM       REPO=https://github.com/SOM-st/JsSOM.git       BUILD=make    SOM=./som.sh
    - env: SOM=PySOM       REPO=https://github.com/SOM-st/PySOM.git       BUILD=""      SOM=./som.sh  PYTHON=python
    - env: SOM=RPySOM      REPO=https://github.com/SOM-st/RPySOM.git      BUILD=""      SOM=./som.sh  PYTHON=python

install:
  - |
    if [ "$SOM" != "spec" ]
    then
      pip install pyyaml
      git clone --depth 1 $REPO som-vm
    fi

# command to run tests
script:
  - |
    set -e
    if [ "$SOM" = "spec" ]
    then
      cd specification
      make test
    else
      ./TestSuite/BasicInterpreterTests/number-of-tests.sh
      export ST_DIR=`pwd`/Smalltalk
      cd som-vm
      git --no-pager log -n 1
      eval $BUILD
      $SOM -cp ../Smalltalk ../TestSuite/TestHarness.som
    fi
